/**
 * DICIONÁRIO OFICIAL DE TERMOS — Sistema ERP Modular
 *
 * Camada central de terminologia para padronizar toda a interface em
 * Português do Brasil (pt-BR), com linguagem profissional de ERP
 * financeiro e contábil brasileiro.
 *
 * REGRA: Todo texto visível ao usuário deve vir daqui.
 * Pode permanecer em inglês apenas: nomes de variáveis, funções,
 * nomes de arquivos e código interno.
 */

export const TERMS = {
  brand: {
    sistema: "Sistema ERP Modular",
  },

  dashboard: {
    tituloPainel: "Painel de Controle",
    subtituloBoasVindas: "Aqui está sua visão financeira em tempo real.",
    resumoFinanceiro: "Resumo Financeiro",
    saldoConsolidado: "Saldo Consolidado",
    resultadoPeriodo: "Resultado do Período",
    variacaoMensal: "Variação Mensal",
    indicadoresPrincipais: "Indicadores Principais",
    visaoConsolidada: "Visão Consolidada do Grupo",
    atualizar: "Atualizar",
    carregandoDados: "Carregando dados financeiros...",
    nenhumaAtividade: "Nenhuma atividade registrada.",
    verLogCompleto: "Ver Log Completo",
    dadosExemplo: "Dados Exemplo",
  },

  financeiro: {
    receita: "Receita",
    receitas: "Receitas",
    despesa: "Despesa",
    despesas: "Despesas",
    entradas: "Entradas",
    saidas: "Saídas",
    fluxoCaixa: "Fluxo de Caixa",
    fluxoCaixa12Meses: "Fluxo de Caixa — 12 Meses",
    fluxoFinanceiro: "Fluxo Financeiro em Tempo Real",
    fluxoLiquido: "Fluxo Líquido",
    saldoCaixa: "Saldo de Caixa",
    saldoEmCaixa: "Saldo em Caixa",
    saldoTotal: "Saldo Total em Conta",
    disponivel: "Disponível",
    previsao: "Previsão",
    compromissos: "Compromissos",
    contasPagar: "Contas a Pagar",
    contasReceber: "Contas a Receber",
    aReceberAberto: "A Receber (Aberto)",
    aPagarAberto: "A Pagar (Aberto)",
    pendenteLiquidacao: "Pendente liquidação",
    proxVencimentos: "Próx. vencimentos",
    inadimplencia: "Índice de Inadimplência",
    inadimplenciaEst: "Inadimplência Est.",
    abaixoMediaSetorial: "Abaixo da média setorial",
    vencimento: "Vencimento",
    pagamento: "Pagamento",
    recebimento: "Recebimento",
    conciliacao: "Conciliação",
    tesouraria: "Tesouraria",
    tesourariaExtrato: "Tesouraria & Extrato",
    receitaMensal: "Receita Mensal",
    indiceLiquidez: "Índice de Liquidez",
    liquidezSaudavel: "Saudável",
    liquidezAtencao: "Em Atenção",
    variacaoPrevio: "+12,4% vs mês anterior",
  },

  contabil: {
    dre: "Demonstrativo de Resultados (DRE)",
    dreSimplificada: "DRE Simplificada",
    receitaBruta: "Receita Bruta",
    deducoes: "(-) Deduções e Impostos",
    receitaLiquida: "Receita Líquida",
    custos: "(-) Custos (CPV/CSP)",
    despesasOperacionais: "(-) Despesas Operacionais",
    lucroLiquido: "Lucro Líquido",
    resultadoLiquido: "Resultado Líquido",
    planoContas: "Plano de Contas",
    balancete: "Balancete",
    lancamentosContabeis: "Lançamentos Contábeis",
    lancamentos: "Lançamentos",
    centroCusto: "Centro de Custo",
    configuracao: "Configuração",
    balanco: "Balanço",
  },

  multiempresa: {
    consolidado: "Consolidado Multiempresa",
    consolidadoMultiEmpresa: "Consolidado Multi-Empresa",
    matriz: "Matriz",
    filial: "Filial",
    grupoEmpresarial: "Grupo Empresarial",
    totalGrupo: "Total Grupo",
    unidade: "Unidade",
    faturamento: "Faturamento",
  },

  compliance: {
    compliance: "Compliance",
    complianceAtivo: "Compliance Ativo",
    auditoria: "Auditoria",
    auditoriaRecente: "Auditoria Recente",
    conformidade: "Conformidade",
    alertas: "Alertas",
    inconsistencias: "Inconsistências",
    logsAuditoria: "Logs de Auditoria",
    sodMonitorado: "Segregação de Funções (SoD) monitorada pelo sistema.",
  },

  auth: {
    acessoPortal: "Acesso ao Portal",
    bemVindoDeVolta: "Bem-vindo de volta ao",
    email: "E-mail",
    senha: "Senha",
    placeholderEmail: "seu@email.com",
    placeholderSenha: "••••••••",
    esqueceuSenha: "Esqueceu a senha?",
    entrarSistema: "Entrar no Sistema",
    abrirEmpresa: "Abrir Minha Empresa Agora",
    semEmpresaRegistrada: "Não tem uma empresa registrada?",
    erroEmailObrigatorio: "O e-mail é obrigatório",
    erroSenhaObrigatoria: "A senha é obrigatória",
    erroLoginFalha: "Falha ao realizar login. Verifique suas credenciais.",
  },

  onboarding: {
    criarEmpresa: "Criar Empresa",
    criarMinhaEmpresa: "Criar Minha Empresa",
  },

  sidebar: {
    inicio: "Início",
    contasBancarias: "Contas Bancarias",
    aplicacoesFinanceiras: "Aplicações Financeiras",
    emprestimos: "Empréstimos",
    parceiros: "Parceiros",
    equipe: "Equipe",
    relatorios: "Relatórios",
    regrasContabeis: "Regras Contábeis",
    portalContador: "Portal Contador",
    operacoesFinanceiras: "Operações Financeiras",
    gestaoCadastros: "Gestão e Cadastros",
    moduloContabil: "Módulo Contábil",
    lancamentoRapido: "Lançamento Rápido",
    alternarEmpresa: "Alternar Empresa",
    aguardandoSetup: "Aguardando Setup",
  },

  landing: {
    gestaoFinanceira: "Gestão Financeira",
    contabilIntegrada: "e Contábil Integrada",
    descricaoHero: "Sistema ERP multi-empresa com módulo contábil completo. Partidas dobradas automáticas, plano de contas por setor, DRE, Balancete e Balanço Patrimonial em tempo real.",
    acessarSistema: "Acessar o Sistema",
    dashboardCentral: "Dashboard Central",
    visaoConsolidadaGrupo: "Visão Consolidada do Grupo",
    metricasGrowth: "Métricas que impulsionam o crescimento",
    metricasDesc: "Distribuição de custos e consolidado multi-empresa para tomada de decisão baseada em dados reais.",
    modulos: "Módulos",
    tudoQueEmpresaPrecisa: "Tudo o que sua empresa precisa",
    ctaTitulo: "Pronto para controlar sua empresa de verdade?",
    ctaDesc: "Junte-se a centenas de empresas que escalaram sua operação financeira com o",
    fazerLogin: "Fazer Login",
    erroCarregamento: "Não foi possível carregar os dados.",
    tecnologias: "Desenvolvido com FastAPI · React · Supabase · SQLModel",
  },

  ui: {
    carregarMais: "Carregar mais",
    voltar: "Voltar",
    continuar: "Continuar",
    salvar: "Salvar",
    cancelar: "Cancelar",
    editar: "Editar",
    excluir: "Excluir",
    filtrar: "Filtrar",
    buscar: "Buscar",
    limpar: "Limpar",
    selecionar: "Selecionar",
    visualizar: "Visualizar",
    detalhes: "Detalhes",
    total: "Total",
    periodo: "Período",
    mes: "Mês",
    meses: "Meses",
    status: "Status",
    loading: "Carregando...",
    erroCarregamento: "Não foi possível carregar os dados.",
    semDados: "Nenhum dado encontrado.",
    dadosSimulados: "Dados simulados",
    dadosSimuladosDescricao: "Conecte sua empresa para visualizar dados reais.",
    aReceber: "A Receber",
    aPagar: "A Pagar",
  },

  graficos: {
    eixoX: "Período",
    eixoY: "Valor",
    legendaReceitas: "Receitas",
    legendaDespesas: "Despesas",
    legendaEntradas: "Entradas",
    legendaSaidas: "Saídas",
    legendaSaldo: "Saldo",
    distribuicaoCustos: "Distribuição de Custos",
    evolucaoCaixa: "Evolução de Caixa",
    crescimentoPatrimonial: "Crescimento Patrimonial",
    receitasVsDespesas: "Receitas vs Despesas — Últimos 6 Meses",
  },
} as const;

export type Terms = typeof TERMS;
