"""fase_1_financeiro

Revision ID: 21d3115ea191
Revises: e8140ed1c89c
Create Date: 2026-04-08 20:09:08.949332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21d3115ea191'
down_revision: Union[str, Sequence[str], None] = 'e8140ed1c89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strict_compliance_sod', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.drop_constraint(batch_op.f('unique_cnpj'), type_='unique')
        batch_op.drop_column('criado_em')
        batch_op.drop_column('atualizado_em')

    with op.batch_alter_table('plano_contas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'plano_contas', ['parent_id'], ['id'])
        batch_op.drop_column('criado_em')
        batch_op.drop_column('atualizado_em')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plano_contas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atualizado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atualizado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('unique_cnpj'), ['cnpj'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('strict_compliance_sod')

    # ### end Alembic commands ###
