"""Initial schema

Revision ID: e8140ed1c89c
Revises: 
Create Date: 2026-03-29 17:26:39.276742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8140ed1c89c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('razao_social', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nome_fantasia', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=False),
    sa.Column('inscricao_estadual', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('inscricao_municipal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('cnae_principal', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('regime_tributario', sa.Enum('SIMPLES_NACIONAL', 'LUCRO_PRESUMIDO', 'LUCRO_REAL', 'MEI', name='regimetributario'), nullable=False),
    sa.Column('cep', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('logradouro', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('numero', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('complemento', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('bairro', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('uf', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('codigo_municipio_ibge', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('configuracoes', sa.JSON(), nullable=True),
    sa.Column('excluido_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_cnpj'), ['cnpj'], unique=True)

    op.create_table('usuarios',
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('convites',
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', name='invitestatus'), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('aceito_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('convites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_convites_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_convites_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_convites_token'), ['token'], unique=True)

    op.create_table('logs_auditoria',
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('acao', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('tabela_afetada', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('registro_id', sa.Uuid(), nullable=False),
    sa.Column('dados_anteriores', sa.JSON(), nullable=True),
    sa.Column('dados_novos', sa.JSON(), nullable=True),
    sa.Column('ip_origem', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logs_auditoria_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('plano_contas',
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo_estruturado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('ATIVO', 'PASSIVO', 'RECEITA', 'DESPESA', 'PATRIMONIO', name='tipoconta'), nullable=False),
    sa.Column('natureza', sa.Enum('DEVEDORA', 'CREDORA', name='naturezaconta'), nullable=False),
    sa.Column('is_analitica', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plano_contas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plano_contas_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('usuario_empresas',
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario_empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_empresas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuario_empresas_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('journal_entries',
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conta_id', sa.Uuid(), nullable=False),
    sa.Column('data_lancamento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('debito_credito', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('historico', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('documento_referencia', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('modulo_origem', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['plano_contas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_entries_conta_id'), ['conta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_data_lancamento'), ['data_lancamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_data_lancamento'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_conta_id'))

    op.drop_table('journal_entries')
    with op.batch_alter_table('usuario_empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_empresas_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_usuario_empresas_empresa_id'))

    op.drop_table('usuario_empresas')
    with op.batch_alter_table('plano_contas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_contas_empresa_id'))

    op.drop_table('plano_contas')
    with op.batch_alter_table('logs_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_auditoria_empresa_id'))

    op.drop_table('logs_auditoria')
    with op.batch_alter_table('convites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_convites_token'))
        batch_op.drop_index(batch_op.f('ix_convites_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_convites_email'))

    op.drop_table('convites')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_cnpj'))

    op.drop_table('empresas')
    # ### end Alembic commands ###
